name: Build and Test the site without deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on pull requests for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3

      # Automatic setup of Ruby environment and dependencies
      - name: Perform Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      # Build the site for static build output tests
      - name: Build jekyll site
        run: bundle exec jekyll build

      # Run static test scripts
      - name: Run Test Scripts
        run: cd _site && bash run_tests.sh

