name: Build the site and run static tests on output

# Controls when the workflow will run
on:
  # Triggers the workflow on pull requests for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # Allows you to control whether to run Cypress Tests when running manually
      run_cypress:
        description: Run Cypress Tests?
        required: true
        default: true
        type: boolean


jobs:
  static-build-test:
    name: Build and run static check scripts
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3

      # Automatic setup of Ruby environment and dependencies
      - name: Perform Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      # Build the site for static build output tests
      - name: Build jekyll site
        run: bundle exec jekyll build

      # Run static test scripts
      - name: Run Test Scripts
        run: bash .run_static_output_tests.sh

  run_cypress:
      # If cypress is to be tested, run cypress-test job
      name: Run Cypress Workflow
      uses: ./.github/workflows/cypress-test.yml
      #with:
      #  run_cypress: ${{ inputs.run_cypress }}
      # I can't figure out how inputs are handled on automatic runs